controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    mech_cont:
      type: mech_drive_controller/MechDriveController

mech_cont:
  ros__parameters:
    wheel_names: 
      - frontRight_joint
      - backLeft_joint
      - frontLeft_joint

    robot_radius: 0.1
    wheel_radius: .024
    gamma: 30.0 # angle between body fixed y axis and the normal of wheel3

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    odom_numeric_integration_method: runge_kutta2

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false