controller_manager:
  ros__parameters:
    update_rate: 15
    #use_sim_time: true

    mech_cont:
      type: mech_drive_controller/MechDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mech_cont:
  ros__parameters:
    publish_rate: 45.0
    base_frame_id: base_link
    odom_frame_id: odom

    wheels_per_side: 2
    front_left_wheel_name: ["frontLeft_joint"]
    front_right_wheel_name: ["frontRight_joint"]
    back_left_wheel_name: ["backLeft_joint"]
    back_right_wheel_name: ["backRight_joint"]
    wheel_separation_width: 0.21
    wheel_separation_length: 0.1665
    wheel_radius: .024
    

    use_stamped_vel: false


    joint_state:
      front_left_wheel:
        topic: "/frontLeft_joint" # Adjust topic names as per your actual topics
        ignore_timestamp: true
      front_right_wheel:
        topic: "/frontRight_joint" # Adjust topic names as per your actual topics
        ignore_timestamp: true
      back_left_wheel:
        topic: "/backLeft_joint" # Adjust topic names as per your actual topics
        ignore_timestamp: true
      back_right_wheel:
        topic: "/backRight_joint" # Adjust topic names as per your actual topics
        ignore_timestamp: true


joint_broad:
  ros__parameters:
    update_rate: 30
    joints: ["frontLeft_joint", "backLeft_joint", "frontRight_joint", "backRight_joint"]
