<?xml version="1.0"?>
<robot name="icarus_pi" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="robot_dimensions.xacro"/>


    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_xoff} 0.0 ${-wheel_zoff}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>
  
     <!-- CHASSIS LINK -->
    <xacro:include filename="Mecanum-8J-Left.urdf.xacro"/>
    <xacro:include filename="Mecanum-Right.urdf.xacro"/>
    <xacro:Mecanum-Right prefix="frontRight" x_reflect="-1" y_reflect="1" r_reflect="${pi/2}"/>
    <xacro:Mecanum-Right prefix="backLeft" x_reflect="1" y_reflect="-1" r_reflect="${pi/2}"/>
    <xacro:Mecanum-Left prefix="frontLeft" x_reflect="-1" y_reflect="-1" r_reflect="${pi/2}"/>
    <xacro:Mecanum-Left prefix="backRight" x_reflect="1" y_reflect="1" r_reflect="${pi/2}"/>

</robot>